name: Build
on: [push]
jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: bin/build.bat
      - uses: actions/upload-artifact@v7
        with: 
          name: assets-for-download
          path: IDE/dist
